# Parameters for Travis CI tests
# These are automated tests that run after each commit
# see: https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.7"
install:
  # install dependencies
  - pip install llvmlite --prefer-binary
  - pip install -r requirements.txt
  - pip install .
  # install testing dependencies
  - pip install pytest>=3.0
  - pip install pytest-cov==2.5.0
  - pip install coveralls
  # install documentation dependencies
  - pip install ipython
  - pip install ipykernel
  - pip install jupyter
  - pip install nbconvert
  - pip install pandoc
  - pip install sphinx>=1.6
  - pip install sphinx_rtd_theme
  - pip install nbsphinx
addons:
  apt_packages:
    - pandoc
script: 
  # run tests
  - py.test ./tests/ --verbose --doctest-modules --color=yes --cov=./qmix/ --cov-report=term-missing
  # build documentation
  - cp notebooks/*.ipynb docs/source/
  - ls docs/source/
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
after_success:
  # for coveralls.io
  - coveralls
deploy:
  # push to github pages
  - provider: pages
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: docs/build/html/
    keep_history: true